# Generated by Django 4.2.5 on 2025-03-30 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Content',
            new_name='content',
        ),
    ]
